@startuml
title InsureTech C4 Container (as-is)
skinparam shadowing false
skinparam linetype ortho
left to right direction
actor "Клиент" as client
rectangle "InsureTech Prod\n[Виртуальная машина]" as prod {
  rectangle "InsureTech Web\n[Container: JavaScript, React]\nВеб-приложение InsureTech" as web
  rectangle "core-app\n[Container: Kotlin, SpringBoot]\nМонолит:\n- отображение продуктов\n- оформление новых страховок\n- отображение оформленных у клиента" as core
  rectangle "client-info\n[Container: Kotlin, SpringBoot]\nСервис для учёта клиентских данных" as clientinfo
  database "ins-comp-settlement-db\n[Container: PostgreSQL]\nБД клиентских данных" as clientdb
  rectangle "ins-product-aggregator\n[Container: Kotlin, SpringBoot]\nАгрегатор продуктов/тарифов страховых компаний" as aggregator
  rectangle "ins-comp-settlement\n[Container: Kotlin, SpringBoot]\nСервис взаиморасчётов со страховыми компаниями" as settlement
  database "ins-comp-settlement-db\n[Container: PostgreSQL]\nБД для расчётов и условий взаиморасчётов" as settlementdb
  database "core-db\n[Container: PostgreSQL]\nБД тарифов, клиентских данных,\nзаявок и страховых продуктов" as coredb
}
rectangle "Платёжный сервис\n[Software System]\nВнешний платёжный сервис" as payment
rectangle "Системы партнёров\n[Software System]\nВнешние партнёры, встраивающие API" as partners
rectangle "Системы страховых компаний\n[Software System]\nВнешние страховые компании" as insurers
' Клиентский путь
client --> web
' Web/API
web --> payment : Проведение оплаты\n(HTTP redirect)
web --> core : 1) Получение тарифов\n2) Создание заявки\n(REST)
partners --> core : Оформление страховок\n(REST)
payment --> core : Проведение оплаты за страховки\n(HTTP)
' Внутренние сервисы и БД
core --> clientinfo : Получение/сохранение\nинформации о клиентах (REST)
clientinfo --> clientdb : Работа с данными (TCP)
core --> coredb : Работа с данными (TCP)
coredb --> core : Получение информации\nоб оформленных страховках (REST)
core --> aggregator : Получение информации\nпо продуктам и тарифам (REST)
settlement --> aggregator : Получение информации\nпо продуктам и тарифам (REST)
settlement --> settlementdb : Работа с данными (TCP)
' Интеграции со страховыми
aggregator --> insurers : Получение информации\nпо продуктам и тарифам\n(REST/SOAP/GraphQL)
settlement --> insurers : Передача данных для взаиморасчётов\n(REST/SOAP/GraphQL)
@enduml