server:
  global:
    scrape_interval: 15s
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false
